{{ if .Values.cni.enabled }}
{{ if or (eq .Values.cni.instanceVersion "v2.0") (eq .Values.cni.instanceVersion "v2.1") (eq .Values.cni.instanceVersion "v2.2") (eq .Values.cni.instanceVersion "v2.3")}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    maistra-version: "2.6.0"
  name: istio-cni
  namespace: {{ .Release.Namespace }}
{{ end }}
{{ end }}
